---
- name: Converge
  hosts: all
  gather_facts: no
  become: yes

  roles:
    - robertdebock.bootstrap
    - robertdebock.epel
    - robertdebock.npm
    - robertdebock.git
    - ansible-role-irslackd
