---
#
# Ansible managed
#
repository:
  description: Install and configure irslackd on your system.
  homepage: https://robertdebock.nl/
  topics: irslackd, development, ansible, molecule, tox, playbook
