---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="centos" tag="latest"
    - image="debian" tag="latest"
    - image="fedora" tag="31"
    - image="fedora" tag="latest"
    - image="opensuse" tag="latest"
    - image="ubuntu" tag="latest"
    - image="ubuntu" tag="bionic"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "fHZxhaH2ZgXjnsN57gwa+LapnCDk6VRdqQkcc+x4i4DjBKZU2eOT9XyJne2FGrvn5CaRQb1AlVYLYN2NfOM1TNnoO0YfoUm/Dz3zg31uOc5kkX+r0xkI1QmSWpL1s+s9ekDKfITjr8t4szAnDSfYS3262H0XX+nJLhYNNtyOX9+zJvj3YdP9Mz9ZnA96MyBXycsKqM5QYTzvHxKpha1r+pgHkg29ArGy1q/qihq93EGsc1O1g/6cfAq5Yt6gMD11xZp2Brjs/BtrPbEouLxG4YLuW77Mfnkc9kiMv2s3K/MCndC/J3FmvfJ/K5nPqCvmoqEgrlVnQuqJSMCXLRh8sRDqEiBPYTuTCu30cP5l+Zq3es3afA6/dpPldBEzw4+MDk6GoX0uNNExIu07NgKDUunw+L8Xgly5W6HWP0+8Z8TjF7hQAbW+S3S8p45PuszAqvmrMJE0cMJiPaYTQokwIDMoKlLigl3XeYg1OFHKoMThwBptaU0PSYDCVsA7eIpRDSS6gRgwUOI+FziI78T/dAJP9LqNX5TRxCPAPHynLOzJP2B1nylB7jMupSJx70wh5iLBzZ7pNT4pRgIBoxBg3UWFb8hBdPAiRO11Qx/F79e2da67Oz92hNZWvNnZsUzFVEnViiAV3MWCgFro9XF4pCQkRyoOFNLjwIhHiCjr0ls="
  email: false
