---
#
# Ansible managed
#
language: python

python:
  - "3.7"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="alpine"
    - image="alpine" tag="edge"
    # - namespace="archlinux" image="base"
    - image="debian" tag="unstable"
    - image="debian"
    - image="centos"
    - image="redhat"
    - image="fedora"
    - image="fedora" tag="rawhide"
    - image="opensuse"
    - image="ubuntu"

matrix:
  allow_failures:
    - env: image="alpine" tag="edge"
    - env: image="debian" tag="unstable"
    - env: image="fedora" tag="rawhide"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: "jk2Dp3ft2u5EXEeA7JFbQ6lsweZQhwwT8kJHVvpGlNaSQUaEh9dvXFX4OU47EqMd7IfKdcuHeOzA92VjmxGyxpQ7Y/67ye+wtSCNWoqvKp2Gh1UXd5Li9FFZPo9dOJABHlVVUJ5BsD4DTcuBiL4n8U0HAh2zbt5X441arXI9jzihHf1ljREzDxl8JcWPbK5jvOXf5cODAJE4JGmFrxliShKbmtnX2PQu68cV4KSkyhvWoLIfx2NVd5WaXkVHgC7k9uNlCrqDdCY5IOfiKlTuhdk5GoJ0jDELBJvBGALBJ+SYx+2yyZfqzLjUCfLbDgelq6fqBvzHWo72PNfvWzFR7VIx1ZeXArOaYlTJAz5YPC+13NuIjtDKT6nG3RMFh5tDDgI4kZFRH+knTKTLBC2Kb2Zxh34CDhlATf1EYJCo8dgYgRIQEcxVrYKAYWYBIXjr6GOF5n9LSuY5C05WNOPVv5825/vHT+VQ+Ka8PQFrvtRkEnSnU1IjMtZlgF1QBcdOi3dcguIHROUR+dw5gLdT2NV4pgruREDkqw8/c5fLF3b9MksfrNthOdVa6RH7ZOq5S/TAl8EKnbhBQEs0oVDw8VUtky67K5fgvKgtaKlJt/jabuNXRtIazIKU4igrl2lOIfKCork2e7I5wp812FQRrF51GURMJqtV973hLd78NN8="
  email: false
