---
#
# Ansible managed
#
language: python

python:
  - "3.8"

services:
  - docker

env:
  global:
    namespace="robertdebock"
  matrix:
    - image="centos" tag="latest"
    - image="debian" tag="latest"
    - image="fedora" tag="31"
    - image="fedora" tag="latest"
    - image="opensuse" tag="latest"
    - image="ubuntu" tag="latest"
    - image="ubuntu" tag="bionic"

cache:
  - pip

install:
  - pip install --upgrade pip
  - pip install tox

script:
  - tox --parallel all

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
  slack:
    secure: Cz8nRDcw09RVhMhJeubRraPvgK8ypZiF0O2G8IMJF4IOCDDYvkNJHdF7m+4qAZokAxhvMaQTajviKO73hLDT9Jg2Kk/RlC3IasMKQlsjsFem6LBBgbgWOHMTl6dhkRAK0tBBH6zj9T7lyDCtqvM+ExBuwWLjdu+1mXflz8r2SR2Kk590qGwNFI3hX6YnLZMfOAJiR8c+fGbgdWGRylLVkScGA/n6kt0+PFqikNSRAbxVwCclNkSmIqMWNA6RSJgZOR0PcHa6QqYFFSMnv2mp5B9PD/s841rVbbscZqqnbTYGNFAbvAZKt+DyJHhplsZ/9y/I+/+Ekhr+E8Pbz51JE/5rqp3b1dx0tYlBMlj1/kXYnyoS0DtwcZY/jHAT30I6J5g1LYFharITTKqaCXXvBjj928B4kWjTwWSM2VcgsbpG8w4X/aT+WuKZDrBxfi1xTyUqP3w7Zxv3U9ccX8nf0RCnbOr2YYWnrm2afinimA/TiI1SfvTYB6OEImpZGsR+o5Nkx+8AtjbQkG+qyS5SAgEoyMZQeVsxtTt8dYSmAPRMm0Be/eimpXGD7+3XXrlq/MzoT8rd+x1urTsNzSZN6Yy8KBMuw3E2TZ8DOrW/GN9druj4Zh8FQDUiN1debOMo2J/C5Ky6CdLMTypnTnExKDLLY8DeqZdjN4aBE+CfbX4=
  email: false
