---

- name: test if irslackd_port is set correctly
  assert:
    that:
      - irslackd_port is defined
      - irslackd_port is number
      - irslackd_port > 0
      - irslackd_port < 65536
    quiet: yes

- name: test if irslackd_address is set correctly
  assert:
    that:
      - irslackd_address is defined
    quiet: yes

- name: test if irslackd_dest is set correctly
  assert:
    that:
      - irslackd_dest is defined
    quiet: yes

- name: test if irslackd_version is set correctly
  assert:
    that:
      - irslackd_version is defined
    quiet: yes

- name: test if irslackd_country is set correctly
  assert:
    that:
      - irslackd_country is defined
    quiet: yes

- name: test if irslackd_state is set correctly
  assert:
    that:
      - irslackd_state is defined
    quiet: yes

- name: test if irslackd_location is set correctly
  assert:
    that:
      - irslackd_location is defined
    quiet: yes

- name: test if irslackd_organization is set correctly
  assert:
    that:
      - irslackd_organization is defined
    quiet: yes

- name: test if irslackd_organizational_unit is set correctly
  assert:
    that:
      - irslackd_organizational_unit is defined
    quiet: yes

- name: test if irslackd_common_name is set correctly
  assert:
    that:
      - irslackd_common_name is defined
    quiet: yes
