---
# tasks file for irslackd
- name: install required software for irslackd
  package:
    name: "{{ irslackd_requirements[ansible_distribution]
          | default(irslackd_requirements['default']) }}"
    state: "{{ irslackd_package_state }}"

- name: create irslackd_dest
  file:
    path: "{{ irslackd_dest }}"
    state: directory
    recurse: yes

- name: install irslackd
  git:
    repo: https://github.com/adsr/irslackd.git
    dest: "{{ irslackd_dest }}"
    version: "{{ irslackd_version }}"
    update: no

- name: install irslackd dependencies
  npm:
    path: "{{ irslackd_dest }}"

- name: save openssl details
  lineinfile:
    path: "{{ irslackd_dest }}/bin/create_tls_key.sh"
    line: "openssl req -newkey rsa:4096 -nodes -sha512 -x509 -days 3650 -nodes -out $dir/cert.pem -keyout $dir/pkey.pem -subj \"/C={{ irslackd_country }}/ST={{ irslackd_state }}/L={{ irslackd_location }}/O={{ irslackd_organization }}/OU={{ irslackd_organizational_unit }}/CN={{ irslackd_common_name }}\""
    regexp: "^openssl"

- name: generate tls key
  command: "{{ irslackd_dest }}/bin/create_tls_key.sh"
  args:
    creates: ~/.irslackd/cert.pem
    chdir: "{{ irslackd_dest }}"

- name: register irslackd to a sysvinit system
  template:
    src: irslackd.j2
    dest: "/etc/init.d/irslackd"
    mode: 0750
  when:
    - ansible_service_mgr == "sysvinit"
      or ansible_service_mgr == "upstart"

- name: register irslackd to a systemd system
  template:
    src: irslackd.service.j2
    dest: /etc/systemd/system/irslackd.service
  when:
    - ansible_service_mgr == "systemd"
  notify:
    - systemctl daemon-reload

- name: flush handlers
  meta: flush_handlers

- name: start irslackd
  service:
    name: irslackd
    state: started
    enabled: true
  when:
    - ansible_virtualization_type != "docker"
