---
# tasks file for irslackd
- name: install required software for irslackd
  package:
    name: "{{ irslackd_requirements }}"
    state: "{{ irslackd_package_state }}"
  register: irslackd_install_required_software_for_irslackd
  until: irslackd_install_required_software_for_irslackd is succeeded
  retries: 3

- name: create irslackd_dest
  file:
    path: "{{ irslackd_dest }}"
    state: directory
    recurse: yes

- name: install irslackd
  git:
    repo: "https://github.com/adsr/irslackd.git"
    dest: "{{ irslackd_dest }}"
    version: "{{ irslackd_version }}"
    update: no

- name: save openssl details
  lineinfile:
    path: "{{ irslackd_dest }}/bin/create_tls_key.sh"
    line: "{{ irslackd_line }}"
    regexp: "^openssl"

- name: generate tls key
  command: "{{ irslackd_dest }}/bin/create_tls_key.sh"
  args:
    creates: ~/.irslackd/cert.pem
    chdir: "{{ irslackd_dest }}"

- name: register irslackd to a sysvinit system
  template:
    src: irslackd.j2
    dest: "/etc/init.d/irslackd"
    mode: 0750
  when:
    - ansible_service_mgr == "sysvinit"
      or ansible_service_mgr == "upstart"

- name: register irslackd to a systemd system
  template:
    src: irslackd.service.j2
    dest: /etc/systemd/system/irslackd.service
  when:
    - ansible_service_mgr == "systemd"
  notify:
    - systemctl daemon-reload

- name: flush handlers
  meta: flush_handlers

- name: start irslackd
  service:
    name: irslackd
    state: started
    enabled: yes
  when:
    - ansible_virtualization_type != "docker" or irslackd_ignore_docker
