---
# tasks file for irslackd
- name: install required software for irslackd
  package:
    name: "{{ irslackd_requirements }}"
    state: present
  register: irslackd_install_required_software_for_irslackd
  until: irslackd_install_required_software_for_irslackd is succeeded
  retries: 3

- name: create irslackd_dest
  file:
    path: "{{ irslackd_dest }}"
    state: directory
    recurse: yes

- name: install irslackd
  git:
    repo: "https://github.com/adsr/irslackd.git"
    dest: "{{ irslackd_dest }}"
    version: "{{ irslackd_version }}"
    update: no

- name: save openssl details
  lineinfile:
    path: "{{ irslackd_dest }}/bin/create_tls_key.sh"
    line: "{{ irslackd_line }}"
    regexp: "^openssl"

- name: generate tls key
  command: "{{ irslackd_dest }}/bin/create_tls_key.sh"
  args:
    creates: ~/.irslackd/cert.pem
    chdir: "{{ irslackd_dest }}"

- name: create irslackd service
  import_role:
    name: robertdebock.service

- name: start irslackd
  service:
    name: irslackd
    state: started
    enabled: yes
