---
# tasks file for irslackd

- name: include assert.yml
  import_tasks: assert.yml
  run_once: yes
  delegate_to: localhost

- name: install required software for irslackd
  package:
    name: "{{ irslackd_requirements }}"
    state: present

- name: create irslackd_dest
  file:
    path: "{{ irslackd_dest }}"
    state: directory
    mode: "0755"

- name: install irslackd
  git:
    repo: "https://github.com/adsr/irslackd.git"
    dest: "{{ irslackd_dest }}"
    version: "{{ irslackd_version }}"
    update: no

- name: Install packages based on package.json.
  npm:
    path: "{{ irslackd_dest }}"

- name: save openssl details
  lineinfile:
    path: "{{ irslackd_dest }}/bin/create_tls_key.sh"
    line: "{{ irslackd_line }}"
    regexp: "^openssl"
    mode: "0755"

- name: generate tls key
  command: "{{ irslackd_dest }}/bin/create_tls_key.sh"
  args:
    creates: ~/.irslackd/cert.pem
    chdir: "{{ irslackd_dest }}"

- name: create irslackd service
  import_role:
    name: robertdebock.service
  vars:
    service_list:
      - name: irslackd
        description: IRC Slack daemon
        start_command: "{{ irslackd_dest }}/irslackd -p {{ irslackd_port }} -a {{ irslackd_address }}"
        working_directory: "{{ irslackd_dest }}"

- name: start irslackd
  service:
    name: irslackd
    state: started
    enabled: yes
