---
# handlers file for irslackd
- name: restart irslackd
  service:
    name: irslackd
    state: restarted
  when:
    - ansible_virtualization_type != "docker"

- name: systemctl daemon-reload
  systemd:
    daemon_reload: yes
  become: yes
  notify:
    - restart irslackd
